### ISSUE TITLE
Multiple issues when loading 1.17.1

### ISSUE THREAD

**Issue by Purplo262** [baguchi/FrostRealm#1]
I ended up with many errors when trying to load the 1.17.1 version of this mod...
![Screen Shot 2021-09-24 at 7 15 58 PM](https://user-images.githubusercontent.com/61368657/134634113-3bd32b43-02a5-44cc-b253-139fb1a864e1.png)

Here is the log: https://pastebin.com/G5D0m58M

**Comment by Npcfanatic21** [comment]
Can you send a screen shot of your mods folder? You could also try taking out optifine and or optiforge

**Comment by DarkDeviants** [comment]
I've also had errors come up, this was after updating forge from 1.17.1-37.0.13 to 1.17.1-37.0.71. Reverting back to the older version of forge allowed for the mod to work.
![Error](https://user-images.githubusercontent.com/91439924/134828960-6707f8d6-a18d-4559-ac0e-4e20aa2a789f.png)

**Comment by baguchi** [comment]
it's fixed on 1.18.1
you can try on newer version
